name: Build using Depot

on:
  workflow_dispatch:
#  push:
#    branches: [release]

jobs:
  publish:
    concurrency:
      group: ${{ github.ref }}-docker
      queue: 'max'
    permissions:
      # allow issuing OIDC tokens for this workflow run
      id-token: write
      # allow for reading the repo contents
      contents: read
      # Allow for pushing to packages
      packages: write
      # Allow for writing attestations for attest action.
      attestations: write
      # Allow for writing artifact metadata for attest action.
      artifact-metadata: write

    runs-on: ubuntu-latest
    strategy:
      matrix:
        atuin_version:
#          - v18.17.1
#          - v18.18.1
          - v18.19.0
#          - v18.20.0-beta.3
#          - main
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Checkout atuin repo
        id: checkout-atuin
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          repository: atuinsh/atuin
          ref: ${{ matrix.atuin_version }}
          path: atuin
          fetch-depth: 0
          persist-credentials: false
          fetch-tags: true

      # This has to be done so atuin-tiny's can be used.
      - name: Remove atuin depot.json
        run: rm atuin/depot.json

      - name: Get and set build information
        id: info
        run: |
          echo "repo_owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "source_date_epoch=$(date --date="$(date --iso-8601=hours)" +%s)" >> $GITHUB_OUTPUT
          echo 'atuin_info<<EOF' >> $GITHUB_OUTPUT
          cat ./atuin-build-info.json >> $GITHUB_OUTPUT
          echo -e '\nEOF' >> $GITHUB_OUTPUT
          cd atuin
          echo "atuin_version=$( git describe --tags )" >> $GITHUB_OUTPUT

      - name: Setup Depot
        id: depot-setup
        uses: depot/setup-action@15c09a5f77a0840ad4bce955686522a257853461 # v1.7.1

      - name: Login to container Registry
        id: ghcr-login
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
        with:
          images: |
            ghcr.io/${{ steps.info.outputs.repo_owner }}/atuin-tiny
          flavor: |
            latest=false
          tags: |
            type=raw,priority=950,value=latest-${{ steps.info.outputs.atuin_version }},enable={{is_default_branch}}
            type=raw,priority=949,value={{branch}}-${{ steps.info.outputs.atuin_version }},enable={{is_not_default_branch}}
            type=sha,prefix=g,suffix=-${{ steps.info.outputs.atuin_version }}
          annotations: |
            org.opencontainers.image.source=https://github.com/csjewell/atuin-tiny
            org.opencontainers.image.url=https://atuin.sh
            org.opencontainers.image.authors=Curtis Jewell and other contributors
            org.opencontainers.image.version=${{ steps.info.outputs.atuin_version }}
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.created={{commit_date 'YYYY-MM-DDTHH:mm:ss.SSS[Z]'}}
            org.opencontainers.image.title=Tiny Atuin Server
            org.opencontainers.image.description=Tiny version of Atuin server image
          labels: |
            org.opencontainers.image.source=https://github.com/csjewell/atuin-tiny
            org.opencontainers.image.url=https://atuin.sh
            org.opencontainers.image.authors=Curtis Jewell and other contributors
            org.opencontainers.image.version=${{ steps.info.outputs.atuin_version }}
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.created={{commit_date 'YYYY-MM-DDTHH:mm:ss.SSS[Z]'}}
            org.opencontainers.image.title=Tiny Atuin Server
            org.opencontainers.image.description=Tiny version of Atuin server image

      - name: Build and push
        id: build
        uses: depot/build-push-action@98e78adca7817480b8185f474a400b451d74e287 # v1.18.0
        env:
          SOURCE_DATE_EPOCH: ${{ steps.info.outputs.source_date_epoch }}
        with:
          outputs: |
            type=registry,push=true,oci-artifact=true,oci-mediatypes=true,rewrite-timestamp=true
          platforms: linux/amd64,linux/arm64
          file: ./${{ fromJson(steps.info.outputs.atuin_info).containerfile[matrix.atuin_version] }}
          context: atuin
          provenance: mode=max,version=v1
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          labels: ${{ steps.meta.outputs.labels }}

#      - name: Attest
#        id: attest
#        uses: actions/attest@v4
#        with:
#          subject-name: ghcr.io/csjewell/atuin-tiny
#          subject-digest: ${{ steps.output.build.digest }}
#          push-to-registry: true
          # I'm not creating an org for this repo. If I was, we could do this.
#          create-storage-record: false



